# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        main:
            entity: { class: AppBundle\Entity\User, property: username }

    encoders:
        AppBundle\Entity\User: sha512

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path:  /login
                check_path:  /login_check
            logout:
                path:   /logout
                target: /

    role_hierarchy:
        ROLE_ADMIN:       ROLE_SONATA_ADMIN

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }