# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    app.job_uploader:
        class: AppBundle\Utils\FileUploader
        arguments: ['%jobs_directory%']
    app.doctrine_job_listener:
        class: AppBundle\EventListener\JobUploadListener
        arguments: ['@app.job_uploader']
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
